name: build

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [8.x,9.x,10.x,11.x,12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and ci
        run: |
          npm install
          npm run build
          npm run ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
